// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJtCb3CsRpBXV-jkZjGkvNZGUV7RhDBk',
    appId: '1:522683234171:web:60ee0ca97d31e4a9716fde',
    messagingSenderId: '522683234171',
    projectId: 'foodapp-6dac3',
    authDomain: 'foodapp-6dac3.firebaseapp.com',
    storageBucket: 'foodapp-6dac3.appspot.com',
    measurementId: 'G-02FJ9QVM4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneJ1k2e1VZc6eo4P2zPwTZuHT4vIHhsg',
    appId: '1:522683234171:android:fa2d497276b6f052716fde',
    messagingSenderId: '522683234171',
    projectId: 'foodapp-6dac3',
    storageBucket: 'foodapp-6dac3.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUJtCb3CsRpBXV-jkZjGkvNZGUV7RhDBk',
    appId: '1:522683234171:web:cbfd1e263a732155716fde',
    messagingSenderId: '522683234171',
    projectId: 'foodapp-6dac3',
    authDomain: 'foodapp-6dac3.firebaseapp.com',
    storageBucket: 'foodapp-6dac3.appspot.com',
    measurementId: 'G-9FZ5TVCDMB',
  );
}
